Repository zolling-paper/backend, pull requests merged in 2025-02, with the labels that each got.

#12 [FEAT] 페이퍼 복수 조회 API에 페이지네이션 적용 (issue #8)
  src/main/java/com/zollingpaper/backend/board/service/BoardService.java
  src/main/java/com/zollingpaper/backend/paper/controller/PaperController.java
  src/main/java/com/zollingpaper/backend/paper/dto/PaperDetailPaginationResponse.java
  src/main/java/com/zollingpaper/backend/paper/repository/PaperRepository.java
  src/main/java/com/zollingpaper/backend/paper/service/PaperService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: ✨ Feature

#15 feat: CORS Config 구성
  src/main/java/com/zollingpaper/backend/global/config/CorsConfig.java
Labels: ✨ Feature

#11 CI/CD 파이프라인 구축
  .github/workflows/backend-cd.yml
  .github/workflows/backend-ci.yml
  Dockerfile
Labels: ✨ Feature

#20 [FEAT] 페이퍼 복수 조회 페이지네이션 prevCursor 응답값 추가 (issue #19)
  src/main/java/com/zollingpaper/backend/paper/dto/PaperDetailPaginationResponse.java
  src/main/java/com/zollingpaper/backend/paper/service/PaperService.java
Labels: ✨ Feature

#21 [ HOT FIX] Docker 이미지 빌드 시 8080포트 매핑 설정 추가 (issue #18)
  .github/workflows/backend-cd.yml
  .github/workflows/backend-ci.yml
  src/main/java/com/zollingpaper/backend/global/config/CorsConfig.java
Labels: 🚨 Hot Fix

#24 [FEAT] board entity에 accessAddress 추가 (issue #14)
  src/main/java/com/zollingpaper/backend/board/controller/BoardController.java
  src/main/java/com/zollingpaper/backend/board/domain/Board.java
  src/main/java/com/zollingpaper/backend/board/dto/BoardDetailResponse.java
  src/main/java/com/zollingpaper/backend/board/dto/BoardSaveResponse.java
  src/main/java/com/zollingpaper/backend/board/repository/BoardRepository.java
  src/main/java/com/zollingpaper/backend/board/service/AccessAddressGenerator.java
  src/main/java/com/zollingpaper/backend/board/service/BoardAccessAddressGenerator.java
  src/main/java/com/zollingpaper/backend/board/service/BoardService.java
  src/main/java/com/zollingpaper/backend/paper/dto/PaperDetailResponse.java
  src/main/java/com/zollingpaper/backend/paper/dto/PaperSaveResponse.java
  src/main/resources/data.sql
  src/test/java/com/zollingpaper/backend/board/controller/BoardControllerE2ETest.java
  src/test/java/com/zollingpaper/backend/board/domain/BoardFixture.java
  src/test/java/com/zollingpaper/backend/paper/controller/PaperControllerE2ETest.java
  src/test/java/com/zollingpaper/backend/paper/domain/PaperFixture.java
Labels: ✨ Feature

#26 [FEAT] board 공개 여부 및 남은 일자 계산 기능 구현 (issue #22)
  src/main/java/com/zollingpaper/backend/board/domain/Board.java
  src/main/java/com/zollingpaper/backend/board/dto/BoardDetailResponse.java
  src/main/java/com/zollingpaper/backend/board/service/BoardService.java
  src/main/resources/data.sql
  src/test/java/com/zollingpaper/backend/board/domain/BoardTest.java
Labels: ✨ Feature

#27 [FEAT] swagger 추가 (issue #25)
  build.gradle
  src/main/java/com/zollingpaper/backend/BackendApplication.java
  src/main/java/com/zollingpaper/backend/board/controller/BoardController.java
  src/main/java/com/zollingpaper/backend/global/config/swagger/SwaggerConfig.java
  src/main/java/com/zollingpaper/backend/global/config/swagger/SwaggerProperties.java
  src/main/java/com/zollingpaper/backend/paper/controller/PaperController.java
  src/main/resources/application.yml
Labels: ✨ Feature, 📃 Docs

#34 [FEAT] Board 비밀번호 형식 검증 로직 추가
  src/main/java/com/zollingpaper/backend/board/domain/Board.java
  src/main/java/com/zollingpaper/backend/board/domain/Password.java
  src/main/java/com/zollingpaper/backend/board/exception/BoardErrorCode.java
  src/test/java/com/zollingpaper/backend/board/domain/PasswordTest.java
Labels: ✨ Feature

#33 [FEAT] CorsConfig URL 추가
  src/main/java/com/zollingpaper/backend/global/config/CorsConfig.java
Labels: ✨ Feature

#35 [FEAT] paper 조회 시 board id uuid를 사용 (issue #30)
  src/main/java/com/zollingpaper/backend/board/service/BoardService.java
  src/main/java/com/zollingpaper/backend/paper/controller/PaperController.java
  src/main/java/com/zollingpaper/backend/paper/dto/PaperSaveRequest.java
  src/main/java/com/zollingpaper/backend/paper/repository/PaperRepository.java
  src/main/java/com/zollingpaper/backend/paper/service/PaperService.java
  src/test/java/com/zollingpaper/backend/paper/controller/PaperControllerE2ETest.java
  src/test/java/com/zollingpaper/backend/paper/domain/PaperFixture.java
Labels: ✨ Feature

#37 [FEAT] paper 목록 조회 시 content 보내지 않도록 변경 (issue #36)
  src/main/java/com/zollingpaper/backend/paper/controller/PaperController.java
  src/main/java/com/zollingpaper/backend/paper/dto/PaperDetailPaginationResponse.java
  src/main/java/com/zollingpaper/backend/paper/dto/PaperDetailResponses.java
  src/main/java/com/zollingpaper/backend/paper/dto/PaperPaginationResponses.java
  src/main/java/com/zollingpaper/backend/paper/dto/PaperResponse.java
  src/main/java/com/zollingpaper/backend/paper/dto/PaperResponses.java
  src/main/java/com/zollingpaper/backend/paper/service/PaperService.java
Labels: ✨ Feature

#39 [HOT FIX] CD Workflow Secret 값 누락 관련 조치
  .github/workflows/backend-cd.yml
Labels: 🚨 Hot Fix

#43 [REFACTOR] docker compose 파일 생성 (issue #42)
  .github/workflows/backend-cd.yml
  compose.yml
  src/main/resources/application.yml
Labels: 🛠️ Refactor

#46 [FEAT] pull request 시에도 ci 작동하도록 변경 (issue #45)
  .github/workflows/backend-ci.yml
Labels: ✨ Feature
